# we are extending everything from tomcat:8.0 image ...
FROM tomcat:10-jdk8
MAINTAINER your_name
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY demo-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
